#!/usr/bin/env ruby
require 'optparse'

options = {}
optparse  = OptionParser.new do |opts|
  opts.banner = 'Usage: lslock <arguments>
    Expected Output: a space delimited list of pids and files
    No output means there are no locked files in the specified directory'
  opts.separator ''
  opts.separator 'Optional Arguments:'
  options[:directory] = '/tmp/lslock-test'
  opts.on('-d', '--directory <path>',
          'the path to look for locked files in (default: /tmp/lslock-test)') do |directory|
    options[:directory] = directory
  end
end
optparse.parse!

abort('You specified a nonexistent directory!
    You may want to make sure lslock_test is running or that you used the -d flag.
    Run lslock -h for more info') unless File.directory? options[:directory]

# let's start by just getting a listing of items in a directory, and their inodes.
files = Dir.glob("#{options[:directory]}/**")
fileshash = {}
files.each do |file|
  # we need to get the full inode, including device ids
  # otherwise, we're not guaranteed to work on boxes with mutliple disks.
  # that would suck.

  # Hoping this works outside of my test env - major device ids are in hex
  maj = File.stat(file).dev_major.to_s(16)
  min = "%02d" % File.stat(file).dev_minor.to_s(16)
  inode = File.stat(file).ino
  fileshash["#{maj}:#{min}:#{inode}"] = "#{file}"
end

# now let's get the list of locks
locks = {}

# I know awk better.
%x(cat /proc/locks | awk {' print $5 ": " $6'}).lines.each do |line|
  line = line.split(' ')
  # use the inode as the key here to make things easier to compare later
  locks.merge! "#{line[1]}" => "#{line[0].chomp(':')}"
end

# now we need to actually find the things that have locks in this directory, 
# and pair them up with pids

locks.sort.each do |inode,pid|
  # some locks don't have a file associated with them
  # we don't care about those, just the ones in the directory we care about.
  #
  # NB - we're using the lock's inode here to reference as the key in the fileshash hash
  if !fileshash[inode].nil? && fileshash[inode].start_with?(options[:directory])
    puts "#{locks[inode]} #{fileshash[inode]}"
  end
end
