#!/usr/bin/env ruby
require 'rubygems'
require 'bazaar'
require 'optparse'
require 'pp'
require 'fileutils'

options = {}
optparse  = OptionParser.new do |opts|
  opts.banner = 'lslock-test --directory <directory>'
  options[:directory] = '/tmp/lslock-test'
  opts.on('-d', '--directory <path>',
          'the directory to create locks in') do |directory|
    options[:directory] = directory
  end
  options[:num_locks] = 10
  opts.on('-n' '--numlocks <integer>',
          'number of locks to create') do |num_locks|
    options[:num_locks] = num_locks
  end
end
optparse.parse!

puts "Will create directory #{options[:directory]} if it does not exist."
FileUtils.mkdir_p options[:directory] unless File.directory? options[:directory]

files = []
options[:num_locks].times do
  files << Bazaar.heroku
end

files.each do |file|
  puts "creating file #{options[:directory]}/#{file}"
  new_file = File.new("#{options[:directory]}/#{file}", 'w')
  new_file.puts file
  new_file.close
end
